# Generated by Django 3.2.9 on 2021-12-04 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='titile',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='titile',
            new_name='title',
        ),
    ]
